name: Publish package to GitHub Packages

on:
  create:

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: chmod +x ./gradlew

      - name: Run Gradle command
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :libpng:publish
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
