name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Gradle command
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: :libpng:assembleRelease
          android-licence: ${{ secrets.ANDROID_LICENCE }}
