name: Publish package to GitHub Packages

on:
  create:

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew :libpng:publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
